#!/bin/bash
#
# tomcat     This shell script takes care of starting and stopping Tomcat
#
# chkconfig: - 80 20
#
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:
# Default-Stop:
# Description: Release implementation for Servlet 2.5 and JSP 2.1
# Short-Description: start and stop report-call
### END INIT INFO

## Source function library.
#. /etc/rc.d/init.d/functions

RED='\033[0;31m'
NC='\033[0m'
GREEN='\033[0;32m'

CURRENT_DIR="/var/lib/report-call-service/"
logPath="$CURRENT_DIR/log_report_call"

function check_report_call(){

        ps -ef | grep report-call-csv-mobi | grep -v "grep" | awk '{print $2}' | wc -l
}

function get_process_pid_report_call(){

	ps -ef | grep report-call-csv-mobi | grep -v "grep" | awk '{print $2}' | awk '{ORS=(NR%3?FS:RS)}1'
}


function kill_process_pid_report_call(){

value_test=`ps -ef | grep report-call-csv-mobi | grep -v "grep" | awk '{print $2}' | awk '{ORS=(NR%3?FS:RS)}1'`

list_pid=(${value_test[@]})
	
	for i in "${!list_pid[@]}";
	do
		if [ "${list_pid[$i]}" -gt "0" ]
			then
			kill -9 ${list_pid[$i]}
		fi
	done
}

function start_report_call(){
	
	if [ `check_report_call` -eq 0 ]
		then
			echo -e "${RED}Service report call is not running....................${NC}"
			"$CURRENT_DIR"/report-call-csv-mobi.sh
			echo -e "${RED}Starting service report call:                                          [${NC}  ${GREEN}OK${NC}  ${RED}]${NC}"
	else
		        echo -e "${RED}Service report call is running....................${NC}"
			echo -e "${RED}Starting service report call:                                          [${NC}  ${GREEN}OK${NC}  ${RED}]${NC}"
	fi
	
}

function stop_report_call(){
	
	if [ `check_report_call` -eq 0 ];
                then
                       echo -e "${RED}Stopping service report call:                                          [${NC}  ${GREEN}OK${NC}  ${RED}]${NC}"
                              

        else	
				sleep 2
                        echo -e "${RED}Stopping service report call: waiting for processes${NC} ${GREEN}`get_process_pid_report_call`${NC} ${RED}to exit [${NC} ${GREEN}OK${NC} ${RED}]${NC}"
				kill_process_pid_report_call		
        fi
}

function restart_report_call(){
	
	stop_report_call
	sleep 2
	start_report_call
}

function status_report_call(){

	if [ `check_report_call` -eq 0 ];
                then
			echo -e "${RED}Service report call is stopped                                         [${NC} ${GREEN}OK${NC} ${RED}]${NC}"

	else
			echo -e "${RED}Sercive report call ${NC}${GREEN}pid `get_process_pid_report_call`${NC}${RED} is running...                          [${NC} ${GREEN}OK${NC} ${RED}]${NC}"
	fi
}

case "$1" in
  start)
    start_report_call
    ;;
  stop)
    stop_report_call
    ;;
  restart)
    restart_report_call
    ;;
  status)
    status_report_call
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0

